### ISSUE TITLE
Error: Cannot find module 'semver'

### ISSUE THREAD

**Issue by jindev** [klaytn/caver-js#154]
**Describe the bug**
can not find moudle semver.

error message.
``` sh
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'semver'
Require stack:
- /Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/scrypt.js
- /Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/index.js
- /Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/src/index.js
- /Users/**/Desktop/test/node_modules/caver-js/index.js
- /Users/**/Desktop/test/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kiheon/Desktop/test-event-logs/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/scrypt.js:30:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/scrypt.js',
    '/Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/index.js',
    '/Users/**/Desktop/test/node_modules/caver-js/packages/caver-klay/src/index.js',
    '/Users/**/Desktop/test/node_modules/caver-js/index.js',
    '/Users/**/Desktop/test/test.js'
  ]
}

```

**How to reproduce**

```
const Caver = require('caver-js')

const caver = new Caver('https://api.baobab.klaytn.net:8651/')

caver.klay.getTransaction('0x2d26f602cfbb4c662931592bf2c4ee18d29f09683be5b9e8d589ff935fca0b97')
  .then(console.log);

```

**Environment (please complete the following information)**
 - nodejs : 12.13.0
- caver-js : 1.2.0
 - os : mac 10.14.6

**Additional context**

It works well after I install `semver`.
```
npm i --S semver
```
I think it should be added `semver` to package.json in caver-js.

**Comment by jimni1222** [comment]
Thank you for reporting a bug.
Fixes for this bug have already been merged in the dev branch.
(Related PR: https://github.com/klaytn/caver-js/pull/152)

Including this change, a version of caver-js v1.2.1 will be released. :) 

This bug has been fixed, so let me close it.
Please let me know if you have any other questions or comments.
