### ISSUE TITLE
TypeError: Cannot read property 'include' of undefined

### ISSUE THREAD

**Issue by hangem422** [klaytn/caver-js#506]
**Describe the bug**
KIP-7 `approve` method error. This bug does not occur in version 1.6.1, but in version 1.6.3.

![error-report01](https://user-images.githubusercontent.com/46883562/128334165-d406bc5f-f65a-4930-a872-8475c50922b2.jpg)

**How to reproduce**
```javascript
if (window.klaytn) {
  const caver = new Caver(window.klaytn);
  const KIP7Instance = new caver.kct.kip7('0x{address in hex}');
  KIP7Instance.approve(
    '0x{address in hex}',
    new BigNumber('0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff'),
    { from: '0x{address in hex}'},
  );
}
```

**Environment (please complete the following information)**
 - caver-js version: 1.6.3
 - Chrome version: 92.0.4515.107
 - Kaikas version: 1.8.1

**Additional context**
I downgraded the version to 1.6.1 and it was resolved.

**Comment by jimni1222** [comment]
Did you add `0x{address in hex` address keyring to the `caver.wallet`?
Please add to the in-memory wallet.

```
const keyring = caver.wallet.keyring.create('0x{address in hex}', '0x{private key}') // or you can use createFromPrivateKey
caver.wallet.add(keyring)
```

**Comment by hangem422** [comment]
This is the front code. Use the **Kaikas** chrome extension program without using key string. If it doesn't support `approve` using Kaikas, why does the same code work without any problem in version 1.6.1?

**Comment by jimni1222** [comment]
Between v1.6.1 ~ v1.6.3, there is some changings for `caver.contract`.
Can you try with v1.6.4-rc.2?

**Comment by hangem422** [comment]
A different error occurs than before. Is there any change in the way to use it? I following [official documents of caver-js](https://ko.docs.klaytn.com/bapp/sdk/caver-js/api-references/caver.kct/kip7#kip7-approve).

![error-report02](https://user-images.githubusercontent.com/46883562/128479667-11ccfa1f-854e-4eee-bf7c-c8516ac1e3c0.jpg)

**Comment by jimni1222** [comment]
@hangem422 
I merged one PR in this regard and deployed caver-js v1.6.4-rc.3.

Please check using the corresponding version.

As the fee delegation model was introduced in caver.contract, the logic to handle the case where there is no keyring in the existing `caver.wallet` has changed.
In the past, `sendTransaction` was used, but this time it was changed to call `sendRawTransaction` after `signTransaction`, but this part was changed to use `sendTransaction` again.

Please check the [PR](https://github.com/klaytn/caver-js/pull/509) for details. Thank you.

**Comment by hangem422** [comment]
A new error occurred using a new version.

```
RPC Error: Error: Params' chain id (0x2019) does not match current network's chain id (8217)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1:66153)
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167996)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167749)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:168176)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270264)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270409
    at new Promise (<anonymous>)
    at new t (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:41:457700)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270198)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1:67505)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1:132743)
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167996)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167749)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:168176)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270264)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270409
    at new Promise (<anonymous>)
    at new t (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:41:457700)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270198)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1:132885)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1:254293
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167996)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:167749)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94:168176)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270264)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28:270361 Object
(anonymous) @ inpage.js:1
```
```
Error: Returned error: Error: Params' chain id (0x2019) does not match current network's chain id (8217)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1)
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28
    at new Promise (<anonymous>)
    at new t (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:41)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1)
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28
    at new Promise (<anonymous>)
    at new t (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:41)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28)
    at t.<anonymous> (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:1
    at b (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator._invoke (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at Generator.forEach.e.<computed> [as next] (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:94)
    at n (chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28)
    at chrome-extension://jblndlipeogpafnldhgmapagcccfchpi/background.js:28
    at Object.ErrorResponse (errors.js:87)
    at index.js:155
    at inpage.js:24
    at inpage.js:1
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at f (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:24
    at inpage.js:24
    at inpage.js:1
    at f (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:24
    at inpage.js:1
    at f (inpage.js:1)
    at inpage.js:1
    at Nt (inpage.js:1)
    at Object.<anonymous> (inpage.js:1)
    at t.value (inpage.js:24)
    at inpage.js:24
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:24
    at n (inpage.js:1)
    at i (inpage.js:1)
    at inpage.js:1
    at inpage.js:24
    at inpage.js:1
    at inpage.js:1
    at f (inpage.js:1)
    at s (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:24
```

**Comment by hangem422** [comment]
If I request chain id of caver right before calling `approve`, it prints 8217. And the mainnet chain id set in my Kaikas extension program is also 8217. Are there any additional properties that need to be set up when using the provider as Kaikas?

```
const id = await web3.klay.getChainId();
console.log(id); // 8217
```

**Comment by jimni1222** [comment]
@hangem422 `0x2019` is hex format of `8217`. I think this issue should be fixed in Kaikas.

**Comment by hangem422** [comment]
@jimni1222 So the format of the caver's chain id has been changed, and is it not compatible with Kaikas?

**Comment by jimni1222** [comment]
It's not incompatible, it's a bug that needs to be fixed in Kaikas.
This bug has been reported and will be fixed soon.

This is not cave-js issue anymore, so i will close this issue.

**Comment by hangem422** [comment]
@jimni1222 Okay. Thank you so much for your quick response.
